version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
        - echo Installing source NPM dependencies...
        - ls
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - npm run ng build --prod
 
artifacts:
    type: zip
    files: '**/*'
